#!/usr/bin/env sh

#
# install-mathjax
#
# Copyright (C) 2009-12 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

# install dir
INSTALL_DIR=`pwd`

# use curl, fetch, or wget
download()
{
  case $(command -v curl || command -v fetch || command -v wget) in
    *curl)  curl -LO https://s3.amazonaws.com/rstudio-buildtools/$1 ;;
    *fetch) fetch https://s3.amazonaws.com/rstudio-buildtools/$1 ;;
    *wget)  wget -O $1 https://s3.amazonaws.com/rstudio-buildtools/$1 ;;
    *)      echo 'ERROR: need curl, fetch, or wget' 1>&2; exit 1 ;;
  esac
}

# download and extract mathjax if necessary
MATHJAX_DIR=mathjax
if [ -d "$MATHJAX_DIR" ]
then
   echo "Mathjax already installed"
else
   MATHJAX=mathjax-20.zip
   download $MATHJAX
   unzip -q "$MATHJAX"
   rm $MATHJAX
fi

# back to install dir
cd $INSTALL_DIR
