#!/usr/bin/env sh

#
# install-dependencies-freebsd
#
# Copyright (C) 2009-13 by RStudio, Inc.
#
# Unless you have received this program directly from RStudio pursuant
# to the terms of a commercial license agreement with RStudio, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

set -e

if [ -e install-overlay ]
then
  ./install-overlay
fi

for package in apache-ant boost-libs cmake e2fsprogs-libuuid libinotify R
do
  pkg_info -E "${package}-*" > /dev/null || pkg_add -r ${package}
done

cd ../common
./install-dictionaries
./install-gwt
./install-mathjax
